"use client"

import { AppBar, Container, Toolbar } from '@mui/material'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{"margin": 0, backgroundColor: '#f5f5f5'}}>
      <AppBar position="static" sx={{ bgcolor: 'white' }} className='px-24 py-3'>
        <Toolbar disableGutters>
          <img src='/logo/FullLogo_Transparent_NoBuffer.png' height={50}/>
        </Toolbar>
      </AppBar>
        {children}
      </body>
    </html>
  )
}
