CURRENT_YEAR = 2023
USELESS_POSITIONS = ["2B/SS", "1B/3B", "IF", "OF", "UTIL", "BE", "IL", "P"]

def lineupSlotOrder(lineupSlot):
    match lineupSlot:
        case "C":
            return 1
        case "1B":
            return 2
        case "2B":
            return 3
        case "3B":
            return 4
        case "SS":
            return 5
        case "2B/SS":
            return 6
        case "1B/3B":
            return 7
        case "LF":
            return 8
        case "CF":
            return 9
        case "RF":
            return 10
        case "OF":
            return 11
        case "UTIL":
            return 12
        case "P":
            return 13
        case "SP":
            return 14
        case "RP":
            return 15
        case "BE":
            return 16
        case "IL":
            return 17
        case _:
            return 18